### ISSUE TITLE
Nether Wart Does Not Grow [1.0.7]

### ISSUE THREAD

**Issue by BlackWingReg** [elucent/Radon#9] opened 2017-07-26 00:03 UTC
Nether wart can be planted on Soul Sand, but doesn't seem to be getting growth ticks. Testing with growth accelerators in creative still didn't see any actual progress towards maturation, in either the Overworld or in the Nether. Placing the netherwart in darkness or underground also doesn't seem to allow it to grow.

**Comment by elucent** [comment] 2017-07-26 06:26
Oh! Sorry, forgot about something. NetherEx requires a fluid called Ichor and Tilled Soul Sand for Nether Wart to grow. I can disable it in config probably though. Closing because this is technically not a bug but please respond if you have additional feedback on if you want the mechanic kept.

https://www.reddit.com/r/NetherEx/wiki/blocks Scroll down to the Tilled Soul Sand or Ichor bits for an explanation of the mechanic.

**Closed as completed by elucent** 2017-07-26 06:26 UTC
